import {DestinationIDs} from "./url-consts";

export const LOCATIONS = [
  {
    ID: "1",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Magic Kingdom",
    TotalRestaurants: 11,
    Slug: "magic-kingdom",
    Images: [],
  },
  {
    ID: "2",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Epcot",
    TotalRestaurants: 21,
    Slug: "epcot",
    Images: [],
  },
  {
    ID: "3",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Hollywood Studios",
    TotalRestaurants: 7,
    Slug: "hollywood-studios",
    Images: [],
  },
  {
    ID: "4",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Fort Wilderness Resort",
    TotalRestaurants: 3,
    Slug: "fort-wilderness-resort",
    Images: [],
  },
  {
    ID: "5",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Contemporary Resort",
    TotalRestaurants: 4,
    Slug: "contemporary-resort",
    Images: [],
  },
  {
    ID: "6",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Polynesian Village",
    TotalRestaurants: 3,
    Slug: "polynesian-village",
    Images: [],
  },
  {
    ID: "7",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Grand Floridian Resort",
    TotalRestaurants: 7,
    Slug: "grand-floridian-resort",
    Images: [],
  },
  {
    ID: "8",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Disney Springs",
    TotalRestaurants: 24,
    Slug: "disney-springs",
    Images: [],
  },
  {
    ID: "10",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Animal Kingdom Resort",
    TotalRestaurants: 5,
    Slug: "animal-kingdom-resort",
    Images: [],
  },
  {
    ID: "11",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Animal Kingdom Lodge",
    TotalRestaurants: 2,
    Slug: "animal-kingdom-lodge",
    Images: [],
  },
  {
    ID: "12",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Animal Kingdom Villas - Kidani Village",
    TotalRestaurants: 1,
    Slug: "animal-kingdom-villas-kidani-village",
    Images: [],
  },
  {
    ID: "14",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Beach Club Resort",
    TotalRestaurants: 2,
    Slug: "beach-club-resort",
    Images: [],
  },
  {
    ID: "16",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "BoardWalk Inn",
    TotalRestaurants: 2,
    Slug: "boardwalk-inn",
    Images: [],
  },
  {
    ID: "17",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Caribbean Beach Resort",
    TotalRestaurants: 2,
    Slug: "caribbean-beach-resort",
    Images: [],
  },
  {
    ID: "18",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Coronado Springs Resort",
    TotalRestaurants: 4,
    Slug: "coronado-springs-resort",
    Images: [],
  },
  {
    ID: "19",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Dolphin Hotel",
    TotalRestaurants: 3,
    Slug: "dolphin-hotel",
    Images: [],
  },
  {
    ID: "20",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Four Seasons Resort",
    TotalRestaurants: 2,
    Slug: "four-seasons-resort",
    Images: [],
  },
  {
    ID: "21",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Old Key West Resort",
    TotalRestaurants: 1,
    Slug: "old-key-west-resort",
    Images: [],
  },
  {
    ID: "23",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Port Orleans Resort - French Quarter",
    TotalRestaurants: 1,
    Slug: "port-orleans-resort-french-quarter",
    Images: [],
  },
  {
    ID: "24",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Saratoga Springs Resort & Spa",
    TotalRestaurants: 1,
    Slug: "saratoga-springs-resort-spa",
    Images: [],
  },
  {
    ID: "25",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Swan Hotel",
    TotalRestaurants: 3,
    Slug: "swan-hotel",
    Images: [],
  },
  {
    ID: "27",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "The Villas at Disney's Wilderness Lodge",
    TotalRestaurants: 2,
    Slug: "the-villas-at-disneys-wilderness-lodge",
    Images: [],
  },
  {
    ID: "29",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Yacht Club Resort",
    TotalRestaurants: 3,
    Slug: "yacht-club-resort",
    Images: [],
  },
  {
    ID: "38",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Boardwalk",
    TotalRestaurants: 1,
    Slug: "boardwalk",
    Images: [],
  },
  {
    ID: "40",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Wilderness Lodge",
    TotalRestaurants: 1,
    Slug: "wilderness-lodge",
    Images: [],
  },
  {
    ID: "41",
    DestinationID: DestinationIDs.Disneyworld,
    DestinationName: "Walt Disney World (Orlando, Florida)",
    Name: "Riviera Resort",
    TotalRestaurants: 1,
    Slug: "riviera-resort",
    Images: [],
  },
  {
    ID: "30",
    DestinationID: DestinationIDs.Disneyland,
    DestinationName: "Disneyland (Anaheim, California)",
    Name: "Disneyland",
    TotalRestaurants: 9,
    Slug: "disneyland",
    Images: [],
  },
  {
    ID: "31",
    DestinationID: DestinationIDs.Disneyland,
    DestinationName: "Disneyland (Anaheim, California)",
    Name: "California Adventure",
    TotalRestaurants: 7,
    Slug: "california-adventure",
    Images: [],
  },
  {
    ID: "32",
    DestinationID: DestinationIDs.Disneyland,
    DestinationName: "Disneyland (Anaheim, California)",
    Name: "Downtown Disney District",
    TotalRestaurants: 9,
    Slug: "downtown-disney-district",
    Images: [],
  },
  {
    ID: "33",
    DestinationID: DestinationIDs.Disneyland,
    DestinationName: "Disneyland (Anaheim, California)",
    Name: "Disneyland Hotel",
    TotalRestaurants: 3,
    Slug: "disneyland-hotel",
    Images: [],
  },
  {
    ID: "34",
    DestinationID: DestinationIDs.Disneyland,
    DestinationName: "Disneyland (Anaheim, California)",
    Name: "Paradise Pier Hotel",
    TotalRestaurants: 1,
    Slug: "paradise-pier-hotel",
    Images: [],
  },
  {
    ID: "35",
    DestinationID: DestinationIDs.Disneyland,
    DestinationName: "Disneyland (Anaheim, California)",
    Name: "Grand Californian",
    TotalRestaurants: 4,
    Slug: "grand-californian",
    Images: [],
  },
];
